### ISSUE TITLE
F-Droid Inclusion

### ISSUE THREAD

**Issue by Popkornium18** [rascarlo/AURdroid#1]
I'd like to add this app to F-Droid, and one requirement is this:

> The original app author has been notified (and supports the inclusion).

Would you support the inclusion?

**Comment by rascarlo** [comment]
I have opened on **F-Droid Request For Packaging** a new issue for inclusion [#180](https://gitlab.com/fdroid/rfp/issues/180).
Thaks for asking

**Comment by rascarlo** [comment]
@Popkornium18 issue closed. the app is now on F-Droid: https://f-droid.org/repository/browse/?fdid=com.rascarlo.aurdroid
