### ISSUE TITLE
AURdroid request 

### ISSUE THREAD

**Issue by miguelosmondo** [rascarlo/AURdroid#14]
Please include the GIT clone address. I can forward these to my company via KDE Connect.

**Comment by rascarlo** [comment]
@miguelosmondo thanks for opening the issue. I see what I can do. The API doesn't expose the git clone url, but after asking on the aurweb development irc, I believe I have found a way to show the url.
thanks

**Comment by rascarlo** [comment]
@miguelosmondo next release will expose the git clone url, as requested (https://github.com/rascarlo/AURdroid/commit/b855978140a3b5e50bd3000c49ec1384e48dfaea).
thanks for opening the issue.
