### ISSUE TITLE
Metadata path

### ISSUE THREAD

**Issue by licaon-kter** [rascarlo/AURdroid#16]
...should be `fastlane/metadata/android/en-US` instead

Ref: https://gitlab.com/fdroid/fdroiddata/issues/1471

**Comment by rascarlo** [comment]
thanks @licaon-kter

**Comment by rascarlo** [comment]
issue closed: https://github.com/rascarlo/AURdroid/commit/07f90cf44ceda5e7ea4e63e10d77f4f4f6bfe9dd
