### ISSUE TITLE
Crash on 2 character search

### ISSUE THREAD

**Issue by stef204** [rascarlo/AURdroid#17]
AURdroid 4.1.7
Nougat

I noticed that if I run some 2 character searches the app crashes.

Example: in the :"Keywords" field:
(Search = "Name or description")

I insert "mp" (without the quotes) and app crashes.

I tried it with other 2 letter combinations and at times it finds a package, at other times it crashes (probably when it finds nothing?)

Can you reproduce?

**Comment by rascarlo** [comment]
Which version are you on?

**Comment by stef204** [comment]
AURdroid 4.1.7 from F-Droid

**Comment by stef204** [comment]
I took a few basic troubleshooting steps:

- clear cache
- clear storage

No change.

- Re-enabled Background data (Settings|Apps|AURdroid|Storage)

No change

- Downgraded to 4.1.6

No change

- Downgraded to 4.1.5

Change: I get the toast/popup -> "Too many package results"

Note 1: on 4.1.7, I never get this toast, even if I perform a search with just the letter "a" as keyword and Search = "Name or description".

On 4.1.5, I also get a different toast if I try to use only 1 character keyword search, such as "m" -> "Query arg too small"

Those 2 toasts are expected/useful.

They do no seem to be present at all in F-Droid versions 4.1.6 and 4.1.7.

Are you sure you are using the F-Droid versions to try to replicate above "bug"?

Note 2:  The same issue is present with your Arch packages app F-Droid version 0.2 , IOW, those 2 toasts do not appear when performing single character searches, it just returns a very long list.  Try it with "a" and Search = "Name or description"

I believe this needs to be looked at.

**Comment by rascarlo** [comment]
Hi I believe there is something wrong.
Version tag 4.1.5 does **not** come with the toast notifications, as you can see in the tag history (https://github.com/rascarlo/AURdroid/commits/v4.1.5)
Version tag 4.1.6 and up comes with the toast notifications, as you can see in the tag history (https://github.com/rascarlo/AURdroid/commits/v4.1.6).

Toast notifications can have different text, according the API error: query too small, too many results, downtime...
Yes I have tried to reproduce the issue on a F-Droid build.
Maybe F-Droid is shipping the wrong tag?
Arch Packages doesn't have the toast notifications implemented yet.

**Comment by stef204** [comment]
Carlo, I misused the term "toast" (IOW and "official or formal toasts") instead of saying: "small popup window drawing on top of the app."

So where I say "toast" anywhere above, replace with "small popup window", please.

To be very precise: I have never seen a toast in either AURdroid or Arch packages (both F-Droid),

**Comment by rascarlo** [comment]
@stef204 tahnks again for keeping this conversation alive and running. thanks to your multiple attemps, I have found out why this crash occurs.
It looks like it is an upstrema bug in the support library, but I have been able to fix it with this commit: https://github.com/rascarlo/AURdroid/commit/fa9f1072ccbf48b862495050015058b5a0b07abb

I will soon publish a new release, if the bug still occurs on the upcoming release, please feel free to comment again. If the bug is fixed, please close the issue.
Thanks again

**Comment by rascarlo** [comment]
The crash is caused by the toast message not being able to correctly draw the text view with font familt monospace. as explained here (https://issuetracker.google.com/issues/64053344#comment3),

> This is a platform issue that was fixed in Android O...
> ... We will also implement this workaround as an automatic fix in AAPT2 for a future release.

stay classy big G!

**Comment by stef204** [comment]
Thanks for being responsive and for your quick turnarounds.
I look forward to the new release and will post here if fixed or still present.
Nice work.

**Comment by stef204** [comment]
Looks good now, getting the "Too many package results."  No crash.  Will close. Thanks.

**Comment by rascarlo** [comment]
@stef204 thanks
