### ISSUE TITLE
5.00: no more black theme?

### ISSUE THREAD

**Issue by vtnpp** [rascarlo/AURdroid#21]
I've just updated to 5.0.0 and noticed that black theme was removed.

Any chance you could bring it back?

Cheers

**Comment by rascarlo** [comment]
V5.0.0 introduced a day night theme. Isn't night dark enough for you?

**Comment by vtnpp** [comment]
It's just that I prefer true black themes over greyish dark ones.

Not a big deal though, I can live with it.

**Comment by rascarlo** [comment]
@vtnpp the night theme is daynight is very black. maybe you are referring to the card view (which is greyish) in the listing?

**Comment by vtnpp** [comment]
No, I'm talking about the startup screen, not about the card view when searching for packages (which is indeed brighter on 0.5.0).

On older versions, there were Dark and Black. I downgraded to 4.2.0 and noticed both were AMOLED black (#000000) and now "Dark" on 0.5.0 is #121212 according to the color picker.

- "Dark" on 4.2.0:
![Screenshot_20200505-000013](https://user-images.githubusercontent.com/59181811/81018291-86f07200-8e64-11ea-871b-877a3492fd7c.jpg)
</details>

- "Black" on on 4.2.0:
![Screenshot_20200505-000025](https://user-images.githubusercontent.com/59181811/81018297-88ba3580-8e64-11ea-9227-a447bc5f3524.jpg)

- "Dark" on 0.5.0:
![Screenshot_20200504-235911](https://user-images.githubusercontent.com/59181811/81018277-81932780-8e64-11ea-9f74-b2e3517756f3.jpg)

I use #000000 everywhere I can (mostly thanks to Swift Installer) but it's fine that the app comes with a dark theme already. :+1:

Feel free to close this.

Cheers.

**Comment by rascarlo** [comment]
@vtnpp ok thanks!
