### ISSUE TITLE
List also packages' co-maintainers

### ISSUE THREAD

**Issue by rffontenelle** [rascarlo/AURdroid#22]
AUR packages can have zero or more co-maintainers, but those co-maintainers are not listed in the package details of AURdroid. Only their main maintainer is listed. Would be nice to list them as well.

Example of packages with co-maintainer: [ddnet](https://aur.archlinux.org/packages/ddnet/) and [pcsx2-git](https://aur.archlinux.org/packages/pcsx2-git/)

**Comment by rascarlo** [comment]
I am aware of such issue. But the api only expose the maintainer
ddnet: https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=ddnet
pcsx2-git: https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pcsx2-git

**Comment by rascarlo** [comment]
closing this issue since I can't do much about it

**Comment by rffontenelle** [comment]
Fair enough. Thanks!

**Comment by rffontenelle** [comment]
For the record, a feature request is already filled in the upstream: https://bugs.archlinux.org/task/57675

**Comment by rascarlo** [comment]
Yes I know. This is why I have added the upstream bug lable.
Unfortunately that bug has been filled long time ago (Wednesday, 28 February 2018, 09:46 GMT ). Hopefully it will be implemented one day
