### ISSUE TITLE
Ideia: Notificar pacotes acompanhados

### ISSUE THREAD

**Issue by gabrielmoura** [rascarlo/AURdroid#9]
Por favor, acrescentar a opção acompanhar pacotes, e ser notificado pelo app de uma nova versão.

**Comment by rascarlo** [comment]
Thanks for opening the issue but such feature will require the use of GooglePlayServices to correctly ensured delivery of notifications. And I don't want to add any dependency to it. You can use the built in enable notification of the AUR if you have an account
